@startuml

title __SQL's Class Diagram__\n

  namespace ub.edu {
    namespace database.dao {
      namespace SQL {
        class ub.edu.resources.dao.SQL.ConnectionFactorySQL {
            {static} - PWD : String
            {static} - URL : String
            {static} - USER : String
            {static} + getConnection()
        }
      }
    }
  }


  namespace ub.edu {
    namespace database.dao {
      namespace SQL {
        class ub.edu.resources.dao.SQL.DAOClientSQL {
            + add()
            + delete()
            + findClientByUserNAmeAndPassword()
            + getAll()
            + getById()
            + update()
            - extractClientFromResultSet()
        }
      }
    }
  }


  namespace ub.edu {
    namespace database.dao {
      namespace SQL {
        class ub.edu.resources.dao.SQL.DAOEpisodiSQL {
            + findAllBySerieAndTemporada()
            - extractEpisodiFromResultSet()
        }
      }
    }
  }


  namespace ub.edu {
    namespace database.dao {
      namespace SQL {
        class ub.edu.resources.dao.SQL.DAOSerieSQL {
            + add()
            + delete()
            + getAll()
            + getById()
            + update()
            - extractSerieFromResultSet()
        }
      }
    }
  }


  namespace ub.edu {
    namespace database.dao {
      namespace SQL {
        class ub.edu.resources.dao.SQL.DAOTemporadaSQL {
            + findAllBySerie()
            - extractTemporadaFromResultSet()
        }
      }
    }
  }


  ub.edu.resources.dao.SQL.DAOClientSQL .up.|> ub.edu.resources.dao.DAOClient
  ub.edu.resources.dao.SQL.DAOSerieSQL .up.|> ub.edu.resources.dao.DAOSerie


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
